export const POPULAR_CITIES = [
  'São Paulo, Brasil',
  'Rio de Janeiro, Brasil',
  'Belo Horizonte, Brasil',
  'Salvador, Brasil',
  'Fortaleza, Brasil',
  'Brasília, Brasil',
  'Curitiba, Brasil',
  'Manaus, Brasil',
  'Recife, Brasil',
  'Porto Alegre, Brasil',
  'Florianópolis, Brasil',
  'Nova York, EUA',
  'Miami, EUA',
  'Orlando, EUA',
  'Los Angeles, EUA',
  'Paris, França',
  'Londres, Reino Unido',
  'Roma, Itália',
  'Lisboa, Portugal',
  'Porto, Portugal',
  'Madri, Espanha',
  'Barcelona, Espanha',
  'Berlim, Alemanha',
  'Amsterdã, Holanda',
  'Buenos Aires, Argentina',
  'Santiago, Chile',
  'Bogotá, Colômbia',
  'Lima, Peru',
  'Tóquio, Japão',
  'Bangkok, Tailândia',
  'Bali, Indonésia',
  'Dubai, Emirados Árabes',
  'Cidade do Cabo, África do Sul',
  'Sydney, Austrália',
  'Toronto, Canadá',
  'Vancouver, Canadá',
];
